apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
  namespace: default
spec:
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
